app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from app import views
from codesvera import settings

app_name = 'app'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('services',views.services, name = 'services'),
    path('career',views.career, name = 'career'),
    path('contact',views.contact, name = 'contact'),
    path('about',views.about, name = 'about'),
    path('carrier-details',views.career_details, name = 'details'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

codesvera/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=25)
    class Meta:
        db_table = 'category'
    def __str__(self):
        return self.category
class Portfolio(models.Model):
    images = models.ImageField(upload_to='portfolio_images/')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    class Meta:
        db_table = 'portfolio'
    def __str__(self):
        return self.category,self.images

class OurClients(models.Model):
    client_name = models.CharField(max_length=100)
    client_comment = models.CharField(max_length=255)
    clent_image = models.ImageField(upload_to='client_images/')
    class Meta:
        db_table = 'client_details'

    def __str__(self):
        return self.clent_image,self.client_comment,self.client_name

app/views.py
from django.shortcuts import render
from .models import Category,OurClients,Portfolio

# Create your views here.
def index(request):
    return render(request,'app/index.html')
def about(request):
    return render(request,'app/about-us.html')
def contact(request):
    return render(request,'app/contact-us.html')









def services(request):
    return render(request,'app/services.html')
def career(request):
    return render(request,'app/career.html')
def career_details(request):
    return render(request,'app/career-details.html')

app/templates/app/career-details.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Codes Vera</title>
      {% load static %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;400;500;700&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;700;800&display=swap" rel="stylesheet">
      <link rel='stylesheet' href="{% static 'assets/owl/rYxrEN.css' %}">
      <link rel='stylesheet' href="{% static 'assets/owl/eezERq.css' %}">
      <link rel='stylesheet' href="{% static 'assets/owl/owl.carousel.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
   </head>
   <style>
   </style>
   <!-- <script src="assets/js/jquery.min.js"></script> -->
   <body>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top ">
         <div class="container nav-cover">
            <a class="navbar-brand" href="#"><img src="{% static 'assets/img/logo.png' %}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
               <ul class="navbar-nav ml-auto mobile-nav">
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:about' %}">About Us</a>
                  </li>
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:services' %}">Services</a>
                  </li>
<!--                  <li class="nav-item">-->
<!--                     <a class="nav-link" href="">Portfolio</a>-->
<!--                  </li>-->
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:career' %}">Career</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:contact' %}">Contact us</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <section class="inner-header">
         <div class="container">
            <h2>Wordpress Developer</h2>
            <ul class="breadcrumb">
               <li><a href="#">Home</a></li>
               <li><a href="#">Career</a></li>
               <li><a href="#">Wordpress Developer</a></li>
            </ul>
         </div>
      </section>
      <section class="details-cover">
         <div class="container">
            <div class="col-lg-8 col-sm-12">
               <div class="details-inner">
                  <h4>
                     Hire Dedicated Wordpress Developer <span style="font-weight:200">In Kochi</span>
                  </h4>
                  <img src="{% static 'assets/img/line.png' %}">
                  <h3>Job Description</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                  <h3>Experience</h3>
                  <p>Minimum of 3 Years relevant experience with JS libraries and ReactJS</p>
                  <h3>Must Have</h3>
                  <ul>
                     <li>Proficient in  ReactJS and other5modern JS libraries/frameworks</li>
                     <li>Proficient in ES6/7 object oriented JavaScript and architecture and development of Single page web applications.</li>
                  </ul>
                  <button>Apply</button>
               </div>
            </div>
         </div>
      </section>
      <footer>
         <div class="container">
            <div class="row">
               <div class="col-lg-4 col-sm-12">
                  <div class="footer-logo">
                     <img src="{% static 'assets/img/logo-footer.png' %}">
                     <p>Door No. 39/2475-b1, Suite127, Lr Towers Sjrra 104, S Janatha Road, Palarivattom Kochi Ernakulam Kl 682025 In</p>
                     <hr>
                     <ul>
                        <a href="mailto:info@codesvera.com">
                           <li>Email : info@codesvera.com</li>
                        </a>
                        <a href="tel:+91 8921162374">
                           <li>Call Us : +91 8921 162 374</li>
                        </a>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-2">
                  <div class="footer-menu">
                     <h3>Quick Links</h3>
                     <ul>
                        <a href="{% url 'app:index' %}">
                           <li>Home</li>
                        </a>
                        <a href="{% url 'app:about' %}">
                           <li>About Us</li>
                        </a>
<!--                        <a href="">-->
<!--                           <li>Portfolio</li>-->
<!--                        </a>-->
                        <a href="{% url 'app:career' %}">
                           <li>Career</li>
                        </a>
                        <a href="{% url 'app:contact' %}">
                           <li>Contact Us</li>
                        </a>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="footer-menu">
                     <h3>We are here</h3>
                     <div>
                        <img src="{% static 'assets/img/map.png' %}">
                     </div>
                  </div>
               </div>
               <div class="col-lg-2 col-sm-12">
                  <div class="footer-social">
                     <h3>Follow Us</h3>
                     <ul>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/linkedin.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/instagram.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/facebook.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/twitter.png' %}">
                           </li>
                        </a>
                     </ul>
                  </div>
               </div>
            </div>
            <h5>© Copyright2019 - All rights reserved | info@Codesvera .com | Privacy Policy | Terms Of Use</h5>
         </div>
      </footer>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'assets/js/jquery-3.4.1.slim.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'assets/owl/jquery.min.js' %}"></script>
      <script src="{% static 'assets/owl/rYxrEN.js' %}"></script>
      <script src="{% static 'assets/owl/owl.carousel.min.js' %}"></script>
      <script  src="{% static 'assets/owl/script.js' %}"></script>
      <script>
         $('.client-inner').owlCarousel({
           loop:true,
           margin:10,
           nav: true,
            dots:false,
           navText: ['<img src="{% static "assets/img/left-nav.png" %}">','<img src="{% static "assets/img/right-nav.png" %}">'],
           responsive:{
               0:{
                   items:1
               },
               600:{
                   items:3
               },
               1000:{
                   items:4
               }
           }
         })
      </script>
   </body>
</html>

app/templates/app/career.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Codes Vera</title>
      {% load static %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;400;500;700&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;700;800&display=swap" rel="stylesheet">
      <link rel='stylesheet' href="{% static 'assets/owl/rYxrEN.css' %}">
      <link rel='stylesheet' href="{% static 'assets/owl/eezERq.css' %}">
      <link rel='stylesheet' href="{% static 'assets/owl/owl.carousel.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
   </head>
   <style>
   </style>
   <!-- <script src="assets/js/jquery.min.js"></script> -->
   <body>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-fixed-top">
         <div class="container nav-cover">
            <a class="navbar-brand" href="#"><img src="{% static 'assets/img/logo.png' %}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
               <ul class="navbar-nav ml-auto mobile-nav">
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:about' %}">About Us</a>
                  </li>
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:services' %}">Services</a>
                  </li>
<!--                  <li class="nav-item">-->
<!--                     <a class="nav-link" href="">Portfolio</a>-->
<!--                  </li>-->
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:career' %}">Career</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'app:contact' %}">Contact us</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <section class="inner-header">
         <div class="container">
            <h2>Career</h2>
            <ul class="breadcrumb">
               <li><a href="#">Home</a></li>
               <li><a href="#">Career</a></li>
            </ul>
         </div>
      </section>
      <section class="career-cover">
         <div class="container">
            <div class="career-head">
               <!-- <h4>OUR PORTFOLIO</h4> -->
               <h2>Work With Us</h2>
               <!-- <h3 class="top-and-bottom">FOR CLIENT</h3> -->
               <img src="{% static 'assets/img/line.png' %}">
               <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
               <div class="row career-inner">
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/1.png' %}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/2.png' %}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/3.png' %}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/4.png'%}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/5.png' %}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                     <div class="career-main clearfix">
                        <div class="career-logo clearfix">
                           <img src="{% static 'assets/img/6.png' %}">
                        </div>
                        <div class="career-text clearfix">
                           <h3>wordpress developer</h3>
                           <a href="{% url 'app:details' %}">Apply Now</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <section>
         <div class="container client-cover">
            <div class="about-content">
               <h2> OUR <span style="font-weight:100">CLIENTS </span></h2>
               <img src="{% static 'assets/img/line.png' %}">
            </div>
            <div class="owl-carousel owl-theme client-inner">
               <div class="item">
                  <img src="{% static 'assets/img/clients-1.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-2.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-3.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-4.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-1.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-3.png' %}">
               </div>
               <div class="item">
                  <img src="{% static 'assets/img/clients-4.png' %}">
               </div>
            </div>
         </div>
      </section>
      <footer>
         <div class="container">
            <div class="row">
               <div class="col-lg-4 col-sm-12">
                  <div class="footer-logo">
                     <img src="{% static 'assets/img/logo-footer.png' %}">
                     <p>Door No. 39/2475-b1, Suite127, Lr Towers Sjrra 104, S Janatha Road, Palarivattom Kochi Ernakulam Kl 682025 In</p>
                     <hr>
                     <ul>
                        <a href="mailto:info@codesvera.com">
                           <li>Email : info@codesvera.com</li>
                        </a>
                        <a href="tel:+91 8921162374">
                           <li>Call Us : +91 8921 162 374</li>
                        </a>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-2">
                  <div class="footer-menu">
                     <h3>Quick Links</h3>
                     <ul>
                        <a href="{% url 'app:index' %}">
                           <li>Home</li>
                        </a>
                        <a href="{% url 'app:about' %}">
                           <li>About Us</li>
                        </a>
<!--                        <a href="">-->
<!--                           <li>Portfolio</li>-->
<!--                        </a>-->
                        <a href="{% url 'app:career' %}">
                           <li>Career</li>
                        </a>
                        <a href="{% url 'app:contact' %}">
                           <li>Contact Us</li>
                        </a>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="footer-menu">
                     <h3>We are here</h3>
                     <div>
                        <img src="{% static 'assets/img/map.png' %}">
                     </div>
                  </div>
               </div>
               <div class="col-lg-2 col-sm-12">
                  <div class="footer-social">
                     <h3>Follow Us</h3>
                     <ul>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/linkedin.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/instagram.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/facebook.png' %}">
                           </li>
                        </a>
                        <a href="#">
                           <li>
                              <img src="{% static 'assets/img/twitter.png' %}">
                           </li>
                        </a>
                     </ul>
                  </div>
               </div>
            </div>
            <h5>© Copyright2019 - All rights reserved | info@Codesvera .com | Privacy Policy | Terms Of Use</h5>
         </div>
      </footer>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'assets/js/jquery-3.4.1.slim.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'assets/owl/jquery.min.js' %}"></script>
      <script src="{% static 'assets/owl/rYxrEN.js' %}"></script>
      <script src="{% static 'assets/owl/owl.carousel.min.js' %}"></script>
      <script  src="{% static 'assets/owl/script.js' %}"></script>
      <script>
         $('.client-inner').owlCarousel({
           loop:true,
           margin:10,
           nav: true,
            dots:false,
           navText: ['<img src="{% static "assets/img/left-nav.png" %}">','<img src="{% static "assets/img/right-nav.png" %}">'],
                    responsive:{
               0:{
                   items:1
               },
               600:{
                   items:3
               },
               1000:{
                   items:4
               }
           }
         })
      </script>
   </body>
</html>

app/templates/app/nav.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Page Title</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>


<style>
 /* CSS used here will be applied after bootstrap.css */
html,body {
  height:100%;
    
}

.first {
  height:100vh;
  min-height:400px;
  background-size:cover;
  background-image:url('https://images.unsplash.com/photo-1470434151738-dc5f4474c239?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb');
}

.affix {
  -webkit-transition:padding 0.2s ease-out;
  -moz-transition:padding 0.2s ease-out;  
  -o-transition:padding 0.2s ease-out;         
  transition:padding 0.2s ease-out;

}

@media (min-width:768px) {
    .affix-top {
      /* navbar style at top */
      background:transparent;
      border-color:transparent;
      padding: 15px;
      -webkit-transition:all 0.5s ease;
      -moz-transition:all 0.5s ease; 
      -o-transition:all 0.5s ease;         
      transition:all 0.5s ease;  
    }
}

.affix-top .nav>li>a {
   color: #000;
}

.affix-top.navbar .nav>li>a:hover,
.affix-top.navbar .navbar-brand
{
   color: #333;
}

section {
  height:calc(90% - 50px);
  height: 90vh;
}

}
</style>
  <body>
   
  <div>
  <div class="navbar navbar-inverse navbar-fixed-top" data-spy="affix" data-offset-top="400">
    <div class="container">
        <div class="navbar-header">
      <a href="#" class="navbar-brand">Brand</a>
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <i class="fa fa-bars"></i>
      </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
        <ul class="nav pull-right navbar-nav">
          <li>
           <a href="#">Link</a>
          </li>
          <li>
            <a href="#"><span class="badge">2</span></a>
          </li>
        </ul>
      </div>        
    </div>
  </div><!-- /.navbar -->
</div>

<section class="first">

  <div class="container">
  
    
  </div>

</section>

<section>

  <div class="container">
  
    <h1>Here is some more content</h1>
    
  </div>

</section>

<section>

  <div class="container">
  
    <h1>Here is some more content</h1>
    
  </div>

</section>

<section>

  <div class="container">
  
    <h1>Here is some more content</h1>
    
  </div>

</section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script></body>



</html>